add a FAQ about NTS DoT deadlock
secureblue/secureblue pull request #274
Opened 2024-05-10 15:11 UTC by czhang03

2024-05-10 15:58 UTC, qoijjj requested changes

2024-05-10 15:58 UTC, qoijjj commented on FAQ.md
> +#### Cannot connect to the internet after boot
this should be in the form of a question. also it should be more specific, like "my system time is way off, why won't it auto update?"

2024-05-10 15:58 UTC, RoyalOughtness commented on FAQ.md
> +Sometimes the system time will be set to a incorrect value after the computer was powered off for a long period of time or a CMOS reset.
These two lines are unnecessary

2024-05-10 15:58 UTC, RoyalOughtness commented on FAQ.md
> +If your system time is off by a significant amount, the above security features will cause a deadlock during time sync.
"If your system time is off by an excessive amount due to rare conditions like a CMOS reset, it must be reset manually and then chrony will work again. This should never be required except under very rare circumstances."

2024-05-10 16:17 UTC, czhang03 commented
Thanks for the review! I have reworded the FAQ.

2024-05-10 19:26 UTC, qoijjj requested changes

2024-05-10 19:26 UTC, qoijjj commented on FAQ.md
> +#### Why Won't My Internet Connect After Boot
question mark and don't capitalize every word

2024-05-10 19:26 UTC, qoijjj commented on FAQ.md
> +If your system time is off by an excessive amount due to rare conditions like a CMOS reset,
put this on one line so the page handles the wrapping

2024-05-11 03:57 UTC, qoijjj approved these changes

2024-05-11 04:00 UTC, merged

2024-05-11 04:01 UTC, qoijjj commented
@czhang03 FYI, I bypassed signature verification to get this merged. Please setup commit verification for future pull requests