feat: add ujust install-negativo(secureblue#504)
secureblue/secureblue pull request #514
Opened 2024-11-01 23:26 UTC by kreativK

Conveniently adds back negativo for users who want it

2024-11-01 23:29 UTC, RoyalOughtness commented on files/system/usr/share/ublue-os/just/70-secureblue.just
> +    sudo curl -o /etc/yum.repos.d/negativo.repo https://negativo17.org/repos/fedora-multimedia.repo
this is in the middle of another command, you need to put it between commands

2024-11-01 23:30 UTC, RoyalOughtness commented on files/system/usr/share/ublue-os/just/70-secureblue.just
> +    sudo curl -o /etc/yum.repos.d/negativo.repo https://negativo17.org/repos/fedora-multimedia.repo
instead of calling sudo for each one, you can just do this:

```
#!/usr/bin/pkexec /usr/bin/bash
```

check some of the other commands above

2024-11-01 23:31 UTC, RoyalOughtness commented on files/system/usr/share/ublue-os/just/70-secureblue.just
> +    sudo curl -o /etc/yum.repos.d/negativo.repo https://negativo17.org/repos/fedora-multimedia.repo
`/etc/yum.repos.d/negativo.repo` could be `/etc/yum.repos.d/negativo17-fedora-multimedia.repo` since there are multiple negativo repos

2024-11-01 23:31 UTC, RoyalOughtness commented on files/system/usr/share/ublue-os/just/70-secureblue.just
> +
otherwise, looks good. thanks for your contribution! :smile:

2024-11-01 23:31 UTC, RoyalOughtness requested changes
See above

2024-11-01 23:33 UTC, RoyalOughtness commented
you might want to also include this

```
sed -i '0,/enabled=1/{s/enabled=1/enabled=1\npriority=90/}' /etc/yum.repos.d/negativo17-fedora-multimedia.repo
```

this will set it to highest priority, so stuff like steam comes from negativo instead of rpmfusion

2024-11-02 21:36 UTC, RoyalOughtness approved these changes

2024-11-02 21:37 UTC, RoyalOughtness commented
lgtm, you just need one more review

2024-11-03 15:01 UTC, Rubiginosa approved these changes

2024-11-03 16:51 UTC, fiftydinar commented
I think that RPMFusion repos need to be disabled also?

At least, Negativo claims it's incompatible:
```
This repository is NOT compatible with RPMFusion, nor it does attempt to replace it as I have no interest in adding any software out there.
```

2024-11-04 06:32 UTC, RoyalOughtness commented
> I think that RPMFusion repos need to be disabled also?
> 
> At least, Negativo claims it's incompatible:
> 
> ```
> This repository is NOT compatible with RPMFusion, nor it does attempt to replace it as I have no interest in adding any software out there.
> ```

yes and yet if secureblue uses negativo for various proprietary packages (which we do because builds constantly break otherwise due to rpmfusion package drift), then negativo is needed for proprietary packages that depend on those packages, like steam.

However, you make a good point @fiftydinar in that maybe we should just be discouraging people from doing that altogether.

@kreativK maybe the right approach here is to edit the FAQ item regarding steam to recommend the [bazzite-arch](https://github.com/ublue-os/bazzite-arch) distrobox instead. With it, users can use steam without layering and without the drawbacks of the flatpak

2024-11-04 14:57 UTC, kreativK commented
> @kreativK maybe the right approach here is to edit the FAQ item regarding steam to recommend the [bazzite-arch](https://github.com/ublue-os/bazzite-arch) distrobox instead. With it, users can use steam without layering and without the drawbacks of the flatpak

Yeah, sounds fair enough. Closing the pull request then👍

2024-11-04 14:57 UTC, closed without merging