doc: document installation of cli packages
secureblue/secureblue pull request #534
Opened 2024-11-07 22:51 UTC by Rubiginosa

2024-11-07 22:53 UTC, Rubiginosa commented
This might close #513, but I'm not sure of that issue's intention.

2024-11-07 23:18 UTC, mkkvcs submitted a review, later dismissed

2024-11-08 01:13 UTC, RoyalOughtness commented on docs/FAQ.md
> +
This seems like a more elaborate version of the FAQ item above it? maybe we can combine them?

2024-11-08 01:18 UTC, RoyalOughtness commented
> This might close #513, but I'm not sure of that issue's intention.

Yep, just documenting that it's preinstalled and preferred

2024-11-08 01:19 UTC, RoyalOughtness requested changes
Let's combine the two FAQ items to cover both GUI and cli packages. Your description is much more elaborate so we can fold them into yours

2024-11-12 17:40 UTC, RoyalOughtness commented
opening this instead https://github.com/secureblue/secureblue/pull/568

2024-11-12 17:51 UTC, RoyalOughtness commented
closing in favor of the above

2024-11-12 17:51 UTC, closed without merging