feat: Flatpak lockdown
secureblue/secureblue pull request #652
Opened 2024-12-07 04:30 UTC by RKNF404

2024-12-13 06:18 UTC, RoyalOughtness commented
lgtm, lmk when this is ready for review

2024-12-13 06:25 UTC, RoyalOughtness commented on files/justfiles/hardening.just
> +    kCommand="flatpak override --user"
since this is only for user flatpaks, can you state this in the comment above

2024-12-13 06:28 UTC, RKNF404 commented on files/justfiles/hardening.just
> +    kCommand="flatpak override --user"
is what I added good?

2024-12-13 06:29 UTC, RoyalOughtness commented on files/justfiles/hardening.just
> +    kCommand="flatpak override --user"
yup

2024-12-13 06:30 UTC, RoyalOughtness approved these changes, later dismissed

2024-12-13 07:34 UTC, TheHooly requested changes

2024-12-13 07:34 UTC, TheHooly commented on files/justfiles/hardening.just
> +    $kCommand --perist=.
Typo: Should be `--persist=.`

2024-12-13 07:34 UTC, TheHooly commented on files/justfiles/hardening.just
> +
`--device=dri` can and should be added by default, some apps rely on getting it via `device=all` and break without it. Practically all apps have and need this permission in some form.

2024-12-13 08:40 UTC, RKNF404 commented on files/justfiles/hardening.just
> +    $kCommand --perist=.
Thanks, fixed

2024-12-13 08:40 UTC, RKNF404 commented on files/justfiles/hardening.just
> +
lmk if there needs to be a better note for that section, otherwise it's done

2024-12-15 08:33 UTC, TheHooly approved these changes

2024-12-15 10:01 UTC, RoyalOughtness approved these changes

2024-12-15 10:12 UTC, merged