Contritubing Documentation
secureblue/secureblue pull request #7
Opened 2023-11-22 18:27 UTC by 34N0

2023-11-22 22:17 UTC, qoijjj commented on CONTRIBUTING.md
> +> If you want to ask a question, ask in the [Issues](https://github.com/secureblue/secureblue/issues).
ask in [Issues]

2023-11-22 22:20 UTC, qoijjj commented on CONTRIBUTING.md
> +### Rebase to DEV image
all of these changes should be done upstream if the upstream documentation is inaccurate

2023-11-22 22:21 UTC, qoijjj requested changes

2023-11-22 22:21 UTC, qoijjj commented on CONTRIBUTING.md
> +First makre sure to edit select the Image you would like to build by editing the `RECIPE` Argument in the Containerfile. Here is an example selecting Silverblue Main:
make

2023-11-22 22:22 UTC, qoijjj commented
The only blocking issue here is that all edits to upstream-relevant documentation should be submitted upstream: https://github.com/ublue-os/startingpoint

Please remove those changes from this PR and it can be merged then.

2023-11-22 22:56 UTC, 34N0 commented
makes perfect sense. I'll submit the changes to CONTRIBUTING.md upstream

2023-11-22 22:59 UTC, qoijjj commented
> makes perfect sense. I'll submit the changes to CONTRIBUTING.md upstream

There are still changes here that are relevant though. like changing the name to secureblue, adding to the readme, and linking to the issues page instead of the discussion page. No need to close the PR :) those changes should still be merged here

2023-11-23 16:55 UTC, 34N0 commented
Removed all the changes in the "Building locally". Left the title and link to issuses.  I'll create a PR with the updated documentation upstream. :-)

2023-11-23 18:17 UTC, merged